### PR TITLE
JDK 8 is now required: update requirements section.

### PR DESCRIPTION
**Pull request by kdvolder**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kdvolder Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-sts&pullRequestId=6)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-sts&pullRequestId=6) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by kdvolder** [comment]
Seriously, I have to sign the CLA, I work for Pivotal? I guess the checking script is confused because I have multiple emails associated with the github account? Or does it not make an exception at all when account is associated with a pivotal.io email address?

**Comment by kdvolder** [comment]
Changed my 'primary' email to pivotal.io. Looks like the check passes now. Seriously though. The script should check the other listed email addresses too.

**Comment by rwinch** [comment]
@kdvolder The script checks all emails. Did you look at https://cla.pivotal.io/faq ?

**Comment by gregturn** [comment]
@kdvolder In the future you can just merge changes to STS guide yourself (you are the expert!)

**Pull request merged**
